"""Generate Home Assistant automations for HA Notifications."""

from __future__ import annotations

import asyncio
import weakref
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar, Protocol

from homeassistant.components.automation import DATA_COMPONENT as AUTOMATION_DATA
from homeassistant.components.automation.config import (
    ValidationStatus,
    async_validate_config,
)
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers import label_registry as lr

from .automation_storage import (
    read_file_bytes_if_exists,
    restore_file,
    write_automation_files,
)
from .configuration import (
    AlertConfig,
    ConfirmationButtonConfig,
    ConfirmationConfig,
    ConfirmationNotificationConfig,
    NotificationConfig,
    ReminderConfig,
)
from .const import AUTOMATION_FILE, AUTOMATION_LABEL

GENERATED_DESCRIPTION = "Generated by HA Notifications. Do not edit manually."

_RECONCILIATION_LOCKS: weakref.WeakKeyDictionary[HomeAssistant, asyncio.Lock] = weakref.WeakKeyDictionary()
_RECONCILIATION_FALLBACK_LOCKS: dict[int, asyncio.Lock] = {}


def _reconciliation_lock(hass: HomeAssistant) -> asyncio.Lock:
    """Return the reconciliation lock for a Home Assistant instance."""
    try:
        return _RECONCILIATION_LOCKS.setdefault(hass, asyncio.Lock())
    except TypeError:
        return _RECONCILIATION_FALLBACK_LOCKS.setdefault(id(hass), asyncio.Lock())


@dataclass(frozen=True, slots=True)
class AutomationFragments:
    """Typed intermediate values assembled before rendering native HA data."""

    triggers: tuple[dict[str, Any], ...] = ()
    conditions: tuple[dict[str, Any], ...] = ()
    active_actions: tuple[dict[str, Any], ...] = ()


class AutomationComponent(Protocol):
    """A deterministic contribution to a generated automation."""

    name: ClassVar[str]
    order: ClassVar[int]

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        """Return the native fragments owned by this component."""


def _confirmation_button_id(
    button: ConfirmationButtonConfig,
    index: int,
) -> str:
    """Return a stable response identifier when the editor leaves it blank."""
    return button.id or f"response_{index + 1}"


class _TriggerComponent:
    name = "trigger"
    order = 10

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        return AutomationFragments(triggers=tuple(alert.triggers))


class _SendComponent:
    name = "send"
    order = 20

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        return AutomationFragments(
            active_actions=(
                {
                    "action": "ha_notifications.send",
                    "data": {
                        "alert_id": alert.id,
                        "alert_name": alert.name,
                        "flow_id": "{{ context.parent_id or context.id }}",
                        **self._confirmation_notification(alert),
                    },
                },
            )
        )

    def notification_mapping(self, notification: NotificationConfig) -> dict[str, Any]:
        """Render typed notification fields without adding default HA keys."""
        mapping: dict[str, Any] = {}
        if notification.target:
            mapping["target"] = dict(notification.target)
        if notification.title:
            mapping["title"] = notification.title
        if notification.message:
            mapping["message"] = notification.message
        if notification.data:
            mapping["data"] = dict(notification.data)
        mapping.update(notification.__pydantic_extra__ or {})
        return mapping

    def _confirmation_notification(self, alert: AlertConfig) -> dict[str, Any]:
        """Add mobile-app response actions to the canonical notification."""
        notification = self.notification_mapping(alert.notification)
        confirmation = alert.confirmation
        if not confirmation or not confirmation.enabled:
            return notification
        data = notification.setdefault("data", {})
        data["actions"] = [
            {
                "action": f"ha_notifications_{alert.id}_confirmation_{_confirmation_button_id(button, index)}",
                "title": button.label,
            }
            for index, button in enumerate(confirmation.buttons)
        ]
        reminders = confirmation.reminders
        timeout = getattr(reminders, "timeout", None)
        if reminders.forget_after_enabled and timeout is not None:
            data["timeout"] = timeout
        return notification


class _ConditionComponent:
    name = "condition"
    order = 15

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        return AutomationFragments(conditions=tuple(alert.conditions))


@dataclass(frozen=True, slots=True)
class _ConfirmationActionFragments:
    """Native confirmation pieces contributed before assembly."""

    wait: dict[str, Any] | None = None
    completion: dict[str, Any] | None = None
    reminders: ReminderConfig | None = None


class _ConfirmationActionComponent(Protocol):
    """A composable contribution to confirmation action assembly."""

    name: ClassVar[str]
    order: ClassVar[int]

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        """Return one or more native confirmation fragments."""


class _ConfirmationWaitComponent:
    name = "wait"
    order = 10

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        timeout = confirmation.reminders.interval
        if timeout is None:
            timeout = {"minutes": 15}
        elif isinstance(timeout, dict):
            timeout = dict(timeout)
        return _ConfirmationActionFragments(
            wait={
                "wait_for_trigger": [
                    {
                        "trigger": "event",
                        "event_type": "mobile_app_notification_action",
                        "event_data": {"action": (f"ha_notifications_{alert.id}_confirmation_{_confirmation_button_id(button, index)}")},
                    }
                    for index, button in enumerate(confirmation.buttons)
                ],
                "timeout": timeout,
                "continue_on_timeout": True,
            }
        )


class _ConfirmationCompletionComponent:
    name = "completion"
    order = 20

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        follow_up = _follow_up_actions(alert, confirmation)
        if not follow_up:
            return _ConfirmationActionFragments()
        return _ConfirmationActionFragments(
            completion={
                "choose": [
                    {
                        "conditions": [
                            {
                                "condition": "template",
                                "value_template": "{{ wait.trigger is not none }}",
                            }
                        ],
                        "sequence": [
                            *follow_up,
                            *_confirmation_completion_actions(alert),
                        ],
                    }
                ]
            }
        )


class _ConfirmationReminderComponent:
    name = "reminder"
    order = 30

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        if not confirmation.reminders.enabled:
            return _ConfirmationActionFragments()
        return _ConfirmationActionFragments(reminders=confirmation.reminders)


class _ConfirmationReminderBuilder:
    """Build the native retry action for configured confirmation reminders."""

    def build(
        self,
        alert: AlertConfig,
        reminders: ReminderConfig | None,
        wait_sequence: Callable[[], list[dict[str, Any]]],
    ) -> dict[str, Any] | None:
        if reminders is None:
            return None
        reminder_notification = _SEND_COMPONENT._confirmation_notification(alert)
        if getattr(reminders, "show_attempts", False) is True:
            reminder_notification = _confirmation_attempt_notification(
                reminder_notification,
                reminders.max_attempts if reminders.max_attempts is not None else 5,
            )
        return {
            "repeat": {
                "count": (reminders.max_attempts if reminders.max_attempts is not None else 5),
                "sequence": [
                    {
                        "action": "ha_notifications.send",
                        "data": {
                            "alert_id": alert.id,
                            "alert_name": alert.name,
                            "flow_id": "{{ context.parent_id or context.id }}",
                            **reminder_notification,
                        },
                    },
                    {
                        "action": "ha_notifications.report",
                        "data": {
                            "alert_id": alert.id,
                            "alert_name": alert.name,
                            "flow_id": "{{ context.parent_id or context.id }}",
                            "status": "confirmation_reminder",
                            "message": "Confirmation reminder sent",
                            "details": {
                                "action": "confirmation_reminder",
                                "repeat": "{{ repeat.index }}",
                            },
                        },
                    },
                    *wait_sequence(),
                ],
            },
        }


def _confirmation_attempt_notification(
    notification: dict[str, Any],
    max_attempts: int,
) -> dict[str, Any]:
    """Add the current retry number to a reminder notification title."""
    notification = dict(notification)
    title = notification.get("title") or "Confirmation"
    notification["title"] = f"{title} - Attempt {{{{ repeat.index + 1 }}}}/{max_attempts}"
    return notification


_CONFIRMATION_ACTION_COMPONENTS: tuple[_ConfirmationActionComponent, ...] = (
    _ConfirmationWaitComponent(),
    _ConfirmationCompletionComponent(),
    _ConfirmationReminderComponent(),
)


def confirmation_action_registry(
    extensions: tuple[_ConfirmationActionComponent, ...] = (),
) -> tuple[_ConfirmationActionComponent, ...]:
    """Return confirmation contributors in stable assembly order."""
    return tuple(
        sorted(
            (*_CONFIRMATION_ACTION_COMPONENTS, *extensions),
            key=lambda component: (component.order, component.name),
        )
    )


class _ConfirmationComponent:
    name = "confirmation"
    order = 30

    def __init__(
        self,
        extensions: tuple[_ConfirmationActionComponent, ...] = (),
    ) -> None:
        self._extensions = extensions

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        if not alert.confirmation or not alert.confirmation.enabled:
            return AutomationFragments()
        return AutomationFragments(active_actions=tuple(self._confirmation_actions(alert)))

    def _confirmation_actions(self, alert: AlertConfig) -> list[dict[str, Any]]:
        """Assemble native confirmation fragments into an action sequence."""
        confirmation = alert.confirmation
        if confirmation is None:
            return []
        components = confirmation_action_registry(self._extensions)

        def build_wait_sequence() -> list[dict[str, Any]]:
            fragments = [component.compose(alert, confirmation) for component in components]
            wait = next(
                (fragment.wait for fragment in fragments if fragment.wait is not None),
                None,
            )
            if wait is None:
                raise ValueError("confirmation action registry must provide a wait")
            completion = next(
                (fragment.completion for fragment in fragments if fragment.completion is not None),
                None,
            )
            return [
                _confirmation_phase_report(
                    alert,
                    "waiting",
                    "confirmation_waiting",
                    "Waiting for confirmation",
                ),
                wait,
                _confirmation_phase_report(
                    alert,
                    "running",
                    "confirmation_resumed",
                    "Confirmation wait finished",
                ),
                *([completion] if completion else []),
            ]

        fragments = [component.compose(alert, confirmation) for component in components]
        reminders = next(
            (fragment.reminders for fragment in fragments if fragment.reminders is not None),
            None,
        )
        reminder_action = _CONFIRMATION_REMINDER_BUILDER.build(
            alert,
            reminders,
            build_wait_sequence,
        )
        return [
            *build_wait_sequence(),
            *([reminder_action] if reminder_action else []),
            {
                "action": "ha_notifications.report",
                "data": {
                    "alert_id": alert.id,
                    "alert_name": alert.name,
                    "flow_id": "{{ context.parent_id or context.id }}",
                    "status": "confirmation_timeout",
                    "run_id": "{{ context.parent_id or context.id }}",
                    "message": "Confirmation timed out",
                    "details": {"action": "confirmation_timeout"},
                },
            },
        ]


class _PostSendComponent:
    name = "post_send"
    order = 25

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        post_send = alert.post_send_actions
        if not post_send or not post_send.get("enabled", False):
            return AutomationFragments()
        actions = [_copy_native_value(action) for action in post_send.get("actions", [])]
        return AutomationFragments(active_actions=tuple(item for action in actions for item in (action, _history_action(alert, action))))


_SEND_COMPONENT = _SendComponent()
_CONFIRMATION_REMINDER_BUILDER = _ConfirmationReminderBuilder()


AUTOMATION_COMPONENTS: tuple[AutomationComponent, ...] = (
    _TriggerComponent(),
    _ConditionComponent(),
    _SEND_COMPONENT,
    _ConfirmationComponent(),
    _PostSendComponent(),
)


def component_registry(
    extensions: tuple[AutomationComponent, ...] = (),
) -> tuple[AutomationComponent, ...]:
    """Return built-ins and extensions in stable composition order."""
    return tuple(
        sorted(
            (*AUTOMATION_COMPONENTS, *extensions),
            key=lambda component: (component.order, component.name),
        )
    )


def compose_automation(
    alert: AlertConfig | dict[str, Any],
    components: tuple[AutomationComponent, ...] | None = None,
) -> AutomationFragments:
    """Compose typed fragments from the ordered component registry."""
    alert = _validated_alert(alert)
    fragments = [component.compose(alert) for component in component_registry(components or ())]
    triggers = tuple(trigger for fragment in fragments for trigger in fragment.triggers)
    conditions = tuple(condition for fragment in fragments for condition in fragment.conditions)
    active_actions = tuple(action for fragment in fragments for action in fragment.active_actions)
    if not triggers:
        raise ValueError(f"alert {alert.id!r} must define at least one evaluation trigger")
    return AutomationFragments(
        triggers=triggers,
        conditions=conditions,
        active_actions=active_actions,
    )


async def async_validate_alerts(
    hass: HomeAssistant,
    alerts: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Validate generated alert automations with Home Assistant's schema."""
    for alert in alerts:
        for index, condition in enumerate(alert.get("conditions", [])):
            if condition.get("condition") != "numeric_state":
                continue
            condition_path = f"Alert {alert['id']!r} conditions[{index}]"
            if not any(key in condition for key in ("above", "below")):
                raise HomeAssistantError(f"{condition_path} (numeric_state) requires at least one of 'above' or 'below'.")
            if "for" in condition:
                raise HomeAssistantError(f"{condition_path} (numeric_state) does not support 'for'; use a state condition when a duration is required.")

    generated_alerts = [alert for alert in alerts if alert.get("triggers")]
    document = [generate_automation(alert) for alert in generated_alerts]
    validated = await async_validate_config(hass, {"automation": document})
    if len(validated["automation"]) != len(document):
        paths = "; ".join(
            f"Alert {alert['id']!r}: "
            + ", ".join(f"conditions[{index}] ({condition.get('condition', 'unknown')})" for index, condition in enumerate(alert.get("conditions", [])))
            for alert in generated_alerts
        )
        raise HomeAssistantError(
            f"Generated HA Notifications automation failed Home Assistant validation; one or more automations were omitted. Condition paths: {paths or 'none'}"
        )
    failures = [
        f"Alert {generated_alerts[index]['id']!r} generated automation has "
        f"validation status {item.validation_status.value!r}"
        + (
            "; condition paths: "
            + ", ".join(
                f"conditions[{condition_index}] ({condition.get('condition', 'unknown')})"
                for condition_index, condition in enumerate(generated_alerts[index].get("conditions", []))
            )
            if item.validation_status == ValidationStatus.FAILED_CONDITIONS
            else ""
        )
        for index, item in enumerate(validated["automation"])
        if item.validation_status != ValidationStatus.OK
    ]
    if failures:
        raise HomeAssistantError("Generated HA Notifications automation failed Home Assistant validation: " + "; ".join(failures))
    return document


def render_automation(
    alert: AlertConfig | dict[str, Any],
    fragments: AutomationFragments,
) -> dict[str, Any]:
    """Render composed fragments as one native Home Assistant automation."""
    alert = _validated_alert(alert)
    action: dict[str, Any] = {
        "choose": [
            {
                "conditions": list(fragments.conditions),
                "sequence": [
                    {
                        "action": "ha_notifications.report",
                        "data": {
                            "alert_id": alert.id,
                            "alert_name": alert.name,
                            "flow_id": "{{ context.parent_id or context.id }}",
                            "status": "started",
                            "run_id": "{{ context.parent_id or context.id }}",
                            "details": {"action": "automation_started"},
                        },
                    },
                    *fragments.active_actions,
                    {
                        "action": "ha_notifications.report",
                        "data": {
                            "alert_id": alert.id,
                            "alert_name": alert.name,
                            "flow_id": "{{ context.parent_id or context.id }}",
                            "status": "completed",
                            "run_id": "{{ context.parent_id or context.id }}",
                            "details": {"action": "automation_completed"},
                        },
                    },
                ],
            }
        ],
    }
    if alert.conditions:
        action["default"] = [
            {
                "action": "ha_notifications.report",
                "data": {
                    "alert_id": alert.id,
                    "alert_name": alert.name,
                    "flow_id": "{{ context.id }}",
                    "status": "inactive",
                    "message": "Condition inactive",
                    "details": {"action": "automation_inactive"},
                },
            },
            {
                "stop": "condition inactive",
            },
        ]
    return {
        "id": automation_id(alert),
        "alias": f"HA Notifications: {alert.name or alert.id}",
        "description": GENERATED_DESCRIPTION,
        "initial_state": alert.enabled,
        "mode": "single",
        "triggers": list(fragments.triggers),
        "conditions": [],
        "actions": [action],
    }


def generate_automation(alert: AlertConfig | dict[str, Any]) -> dict[str, Any]:
    """Generate one Home Assistant automation for an alert."""
    validated = _validated_alert(alert)
    return render_automation(validated, compose_automation(validated))


def _validated_alert(alert: AlertConfig | dict[str, Any]) -> AlertConfig:
    """Accept persisted mappings while keeping automation on validated models."""
    return alert if isinstance(alert, AlertConfig) else AlertConfig.model_validate(alert)


def _history_action(alert: AlertConfig, action: dict[str, Any]) -> dict[str, Any]:
    """Build the explicit history action paired with one native action."""
    action_name = action.get("action", "automation action")
    return {
        "action": "ha_notifications.record",
        "data": {
            "alert_id": alert.id,
            "alert_name": alert.name,
            "flow_id": "{{ context.parent_id or context.id }}",
            "details": {"action": action_name},
        },
    }


def _follow_up_actions(
    alert: AlertConfig,
    confirmation: ConfirmationConfig,
) -> list[dict[str, Any]]:
    """Convert configured confirmation actions to native HA actions."""
    actions: list[dict[str, Any]] = []
    notification = confirmation.notification
    if (
        notification.enabled is not False
        and (
            notification.action
            or notification.target is not None
            or notification.title is not None
            or notification.message is not None
            or notification.data is not None
        )
    ):
        notification = _confirmation_notification_mapping(notification, alert.notification.target)
        data = dict(notification.get("data", {}))
        message = data.pop("message", None)
        if isinstance(message, str) and message:
            data["template_message"] = "{% raw %}" + message + "{% endraw %}"
            data["confirmation_device_id"] = "{{ wait.trigger.event.data.device_id | default('', true) }}"
            data["confirmation_user_id"] = "{{ wait.trigger.event.context.user_id | default('', true) }}"
        if data:
            notification["data"] = data
        actions.append(
            {
                "action": "ha_notifications.send",
                "data": {
                    "alert_id": alert.id,
                    "alert_name": alert.name,
                    "flow_id": "{{ context.parent_id or context.id }}",
                    **notification,
                },
            }
        )
    configured_actions = confirmation.actions
    if isinstance(configured_actions, dict):
        configured_actions = configured_actions.get("items", [])
    native_actions = [_copy_native_value(action) for action in configured_actions]
    return [item for action in actions for item in (action,)] + [item for action in native_actions for item in (action, _history_action(alert, action))]


def _confirmation_completion_actions(alert: AlertConfig) -> list[dict[str, Any]]:
    """Report confirmation completion and stop the finished automation."""
    return [
        {
            "action": "ha_notifications.report",
            "data": {
                "alert_id": alert.id,
                "alert_name": alert.name,
                "flow_id": "{{ context.parent_id or context.id }}",
                "status": "confirmation_completed",
                "run_id": "{{ context.parent_id or context.id }}",
                "message": "Confirmation completed",
                "details": {
                    "action": "confirmation_completed",
                    "device_id": ("{{ wait.trigger.event.data.device_id | default('', true) }}"),
                    "user_id": ("{{ wait.trigger.event.context.user_id | default('', true) }}"),
                },
            },
        },
        {"stop": "confirmation completed"},
    ]


def _confirmation_phase_report(
    alert: AlertConfig,
    status: str,
    action: str,
    message: str,
) -> dict[str, Any]:
    """Build a report for a confirmation wait phase."""
    return {
        "action": "ha_notifications.report",
        "data": {
            "alert_id": alert.id,
            "alert_name": alert.name,
            "flow_id": "{{ context.parent_id or context.id }}",
            "status": status,
            "run_id": "{{ context.parent_id or context.id }}",
            "message": message,
            "details": {"action": action},
        },
    }


def _confirmation_notification_mapping(
    notification: ConfirmationNotificationConfig,
    fallback_target: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Convert a confirmation notification to the managed service payload."""
    action: dict[str, Any] = {}
    target = notification.target if notification.target is not None else fallback_target
    if target:
        action["target"] = dict(target)
    data = dict(notification.data or {})
    if notification.title is not None:
        data.setdefault("title", notification.title)
    if notification.message is not None:
        data.setdefault("message", notification.message)
    if data:
        action["data"] = data
    action.update(notification.__pydantic_extra__ or {})
    return action


def _copy_native_value(value: Any) -> Any:
    """Create fresh containers for repeated Home Assistant native values."""
    if isinstance(value, dict):
        return {key: _copy_native_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_copy_native_value(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_copy_native_value(item) for item in value)
    return value


def automation_id(alert: AlertConfig | dict[str, Any]) -> str:
    """Return the stable automation ID for an alert."""
    alert_id = alert.id if isinstance(alert, AlertConfig) else alert["id"]
    return f"ha_notifications_{alert_id}"


def ensure_automation_include(
    path: Path,
) -> bool:
    """Ensure the dedicated generated automation include is configured."""
    include_line = f"automation ha_notifications: !include {AUTOMATION_FILE}\n"
    content = path.read_text() if path.exists() else ""
    if include_line.rstrip("\n") in content.splitlines():
        return False
    separator = "" if not content or content.endswith("\n") else "\n"
    path.write_text(f"{content}{separator}{include_line}")
    return True


def automation_status(
    document: list[dict[str, Any]],
    alert: dict[str, Any],
) -> str:
    """Return the ownership/status projection for one generated automation."""
    if alert.get("automation", {}).get("ownership") == "manual":
        return "manual"

    generated = next(
        (item for item in document if item.get("id") == automation_id(alert)),
        None,
    )
    if generated is None:
        return "missing"
    if generated.get("description") != GENERATED_DESCRIPTION:
        return "conflict"
    if generated.get("initial_state") is False:
        return "disabled"
    return "managed"


async def async_reconcile_automations(
    hass: HomeAssistant,
    alerts: list[dict[str, Any]],
    _affected_ids: set[str] | None = None,
) -> list[dict[str, Any]]:
    """Reconcile managed automations and reload Home Assistant's collection."""
    lock = _reconciliation_lock(hass)
    async with lock:
        path = Path(hass.config.path(AUTOMATION_FILE))
        configuration_path = Path(hass.config.path("configuration.yaml"))
        await hass.async_add_executor_job(
            ensure_automation_include,
            configuration_path,
        )
        document = await async_validate_alerts(hass, alerts)
        original = await hass.async_add_executor_job(read_file_bytes_if_exists, path)
        try:
            await hass.async_add_executor_job(write_automation_files, path, document)
            await hass.services.async_call("automation", "reload", blocking=True)
            _label_generated_automations(hass, document)
        except Exception:
            await hass.async_add_executor_job(restore_file, path, original)
            raise
        return document


def _label_generated_automations(
    hass: HomeAssistant,
    document: list[dict[str, Any]],
) -> None:
    """Assign the managed label to generated automation entities."""
    component = getattr(hass, "data", {}).get(AUTOMATION_DATA)
    if component is None:
        return
    label_registry = lr.async_get(hass)
    label = label_registry.async_get_label_by_name(AUTOMATION_LABEL)
    if label is None:
        label = label_registry.async_create(
            AUTOMATION_LABEL,
            description="Automations generated by HA Notifications.",
        )
    entity_registry = er.async_get(hass)
    generated_ids = {item["id"] for item in document}
    for entity in getattr(component, "entities", ()):
        if getattr(entity, "unique_id", None) not in generated_ids:
            continue
        registry_entry = entity_registry.async_get(entity.entity_id)
        if registry_entry is None or label.label_id in registry_entry.labels:
            continue
        entity_registry.async_update_entity(
            entity.entity_id,
            labels=set(registry_entry.labels) | {label.label_id},
        )
