"""Generate Home Assistant automations for HA Notifications."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Protocol

from homeassistant.components.automation.config import (
    ValidationStatus,
    async_validate_config,
)
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError

from .configuration import (
    AlertConfig,
    ConfirmationButtonConfig,
    ConfirmationConfig,
    ConfirmationNotificationConfig,
    NotificationConfig,
    ReminderConfig,
    _duration_seconds,
)
from .const import (
    COMMAND_CANCEL_RUN,
    COMMAND_SKIP_CONFIRMATION,
    EVENT_COMMAND,
)

GENERATED_DESCRIPTION = "Generated by HA Notifications. Do not edit manually."

@dataclass(frozen=True, slots=True)
class AutomationFragments:
    """Typed intermediate values assembled before rendering native HA data."""

    triggers: tuple[dict[str, Any], ...] = ()
    conditions: tuple[dict[str, Any], ...] = ()
    actions: tuple[dict[str, Any], ...] = ()


class AutomationComponent(Protocol):
    """A deterministic contribution to a generated automation."""

    name: ClassVar[str]
    order: ClassVar[int]

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        """Return the native fragments owned by this component."""


def _confirmation_button_id(
    button: ConfirmationButtonConfig,
    index: int,
) -> str:
    """Return a stable response identifier when the editor leaves it blank."""
    return button.id or f"response_{index + 1}"


class _TriggerComponent:
    name = "trigger"
    order = 10

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        return AutomationFragments(triggers=tuple(alert.monitor.enabled_triggers))


class _SendComponent:
    name = "send"
    order = 20

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        steps = _ActionStepBuilder(alert)
        return AutomationFragments(
            actions=(
                steps.send(self._confirmation_notification(alert)),
            )
        )

    @staticmethod
    def notification_mapping(notification: NotificationConfig) -> dict[str, Any]:
        """Render typed notification fields without adding default HA keys."""
        mapping: dict[str, Any] = {}
        if notification.target:
            mapping["target"] = dict(notification.target)
        if notification.title:
            mapping["title"] = notification.title
        if notification.message:
            mapping["message"] = notification.message
        if notification.data:
            mapping["data"] = dict(notification.data)
        mapping.update(notification.__pydantic_extra__ or {})
        return mapping

    def _confirmation_notification(self, alert: AlertConfig) -> dict[str, Any]:
        """Add mobile-app response actions to the canonical notification."""
        notification = self.notification_mapping(alert.notification)
        confirmation = alert.confirmation
        if not confirmation or not confirmation.enabled:
            return notification
        data = notification.setdefault("data", {})
        data["actions"] = [
            {
                "action": f"ha_notifications_{alert.id}_confirmation_{_confirmation_button_id(button, index)}",
                "title": button.label,
            }
            for index, button in enumerate(confirmation.buttons)
        ]
        reminders = confirmation.reminders
        timeout = getattr(reminders, "timeout", None)
        if reminders.forget_after_enabled and timeout is not None:
            data["timeout"] = _duration_seconds(timeout)
        return notification


class _ConditionComponent:
    name = "condition"
    order = 15

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        condition_options = alert.monitor.conditions
        conditions = condition_options.items if condition_options.enabled else []
        return AutomationFragments(conditions=tuple(conditions))


class _ActionStepBuilder:
    """Build generated service and history steps for one alert."""

    def __init__(self, alert: AlertConfig) -> None:
        self._alert = alert

    def _service(self, action: str, data: dict[str, Any]) -> dict[str, Any]:
        return {"action": action, "data": data}

    def send(self, notification: dict[str, Any]) -> dict[str, Any]:
        """Build a managed send action with alert and flow metadata."""
        return self._service(
            "ha_notifications.send",
            {
                "alert_id": self._alert.id,
                "alert_name": self._alert.name,
                "flow_id": "{{ context.parent_id or context.id }}",
                **notification,
            },
        )

    def report(
        self,
        status: str,
        action: str,
        *,
        message: str | None = None,
        details: dict[str, Any] | None = None,
        flow_id: str = "{{ context.parent_id or context.id }}",
        include_run_id: bool = True,
    ) -> dict[str, Any]:
        data: dict[str, Any] = {
            "alert_id": self._alert.id,
            "alert_name": self._alert.name,
            "flow_id": flow_id,
            "status": status,
        }
        if include_run_id:
            data["run_id"] = flow_id
        if message is not None:
            data["message"] = message
        data["details"] = details if details is not None else {"action": action}
        return self._service("ha_notifications.report", data)

    def action_executed(self, native_action: dict[str, Any]) -> dict[str, Any]:
        """Build a lifecycle report for one successfully executed action."""
        return self.report(
            "action_executed",
            "action_executed",
            message="Automation action executed",
            details={"action": native_action.get("action", "automation action")},
        )

    def recorded_action(
        self,
        native_action: dict[str, Any],
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        return native_action, self.action_executed(native_action)

    def stop(
        self,
        reason: str,
        status: str,
        action: str,
        message: str,
        details: dict[str, Any],
        *,
        flow_id: str = "{{ context.parent_id or context.id }}",
        include_run_id: bool = True,
    ) -> list[dict[str, Any]]:
        return [
            self.report(
                status,
                action,
                message=message,
                details=details,
                flow_id=flow_id,
                include_run_id=include_run_id,
            ),
            {"stop": reason},
        ]


@dataclass(frozen=True, slots=True)
class _ConfirmationActionFragments:
    """Native confirmation pieces contributed before assembly."""

    wait: dict[str, Any] | None = None
    completion: tuple[dict[str, Any], ...] | None = None
    reminders: ReminderConfig | None = None


class _ConfirmationActionComponent(Protocol):
    """A composable contribution to confirmation action assembly."""
    name: ClassVar[str]
    order: ClassVar[int]

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        """Return one or more native confirmation fragments."""


class _ConfirmationWaitComponent:
    name = "wait"
    order = 10

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        timeout = confirmation.reminders.interval
        if timeout is None:
            timeout = {"minutes": 15}
        elif isinstance(timeout, dict):
            timeout = dict(timeout)
        return _ConfirmationActionFragments(
            wait={
                "wait_for_trigger": [
                    {
                        "trigger": "event",
                        "event_type": "mobile_app_notification_action",
                        "id": "confirmation",
                        "event_data": {"action": (f"ha_notifications_{alert.id}_confirmation_{_confirmation_button_id(button, index)}")},
                    }
                    for index, button in enumerate(confirmation.buttons)
                ]
                + [
                    {
                        "trigger": "event",
                        "event_type": EVENT_COMMAND,
                        "id": "cancel_run",
                        "event_data": {
                            "alert_id": alert.id,
                            "command": COMMAND_CANCEL_RUN,
                        },
                    },
                    {
                        "trigger": "event",
                        "event_type": EVENT_COMMAND,
                        "id": "skip_confirmation",
                        "event_data": {
                            "alert_id": alert.id,
                            "command": COMMAND_SKIP_CONFIRMATION,
                        },
                    }
                ],
                "timeout": timeout,
                "continue_on_timeout": True,
            }
        )


class _ConfirmationCompletionComponent:
    name = "completion"
    order = 20

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        steps = _ActionStepBuilder(alert)
        follow_up = _follow_up_actions(alert, confirmation, steps)
        return _ConfirmationActionFragments(
            completion=(
                steps.report(
                    "confirmation_completed",
                    "confirmation_completed",
                    message="Confirmation completed",
                    details={
                        "action": "confirmation_completed",
                        "device_id": (
                            "{{ wait.trigger.event.data.device_id | default('', true) }}"
                        ),
                        "user_id": (
                            "{{ wait.trigger.event.context.user_id | default('', true) }}"
                        ),
                    },
                ),
                *follow_up,
                {"stop": "confirmation completed"},
            ),
        )


class _ConfirmationReminderComponent:
    name = "reminder"
    order = 30

    def compose(
        self,
        alert: AlertConfig,
        confirmation: ConfirmationConfig,
    ) -> _ConfirmationActionFragments:
        if not confirmation.reminders.enabled:
            return _ConfirmationActionFragments()
        return _ConfirmationActionFragments(reminders=confirmation.reminders)


class _ConfirmationReminderBuilder:
    """Build the native retry action for configured confirmation reminders."""

    def build(
        self,
        alert: AlertConfig,
        reminders: ReminderConfig | None,
        wait: dict[str, Any],
        outcome_branches: tuple[dict[str, Any], ...],
        steps: _ActionStepBuilder,
    ) -> dict[str, Any] | None:
        if reminders is None:
            return None
        reminder_notification = _SEND_COMPONENT._confirmation_notification(alert)
        if getattr(reminders, "show_attempts", False) is True:
            reminder_notification = _confirmation_attempt_notification(
                reminder_notification,
                reminders.max_attempts if reminders.max_attempts is not None else 5,
            )
        return {
            "repeat": {
                "count": (reminders.max_attempts if reminders.max_attempts is not None else 5),
                "sequence": [
                    steps.send(reminder_notification),
                    steps.report(
                        "confirmation_reminder",
                        "confirmation_reminder",
                        message="Confirmation reminder sent",
                        details={
                            "action": "confirmation_reminder",
                            "repeat": "{{ repeat.index }}",
                        },
                        include_run_id=False,
                    ),
                    steps.report("waiting", "confirmation_waiting", message="Waiting for confirmation"),
                    _copy_native_value(wait),
                    {
                        "choose": [
                            *[
                                _copy_native_value(branch)
                                for branch in outcome_branches
                            ],
                        ],
                        "default": [],
                    },
                ],
            },
        }


def _confirmation_attempt_notification(
    notification: dict[str, Any],
    max_attempts: int,
) -> dict[str, Any]:
    """Add the current retry number to a reminder notification title."""
    notification = dict(notification)
    title = notification.get("title") or "Confirmation"
    notification["title"] = f"{title} - Attempt {{{{ repeat.index + 1 }}}}/{max_attempts}"
    return notification


_CONFIRMATION_ACTION_COMPONENTS: tuple[_ConfirmationActionComponent, ...] = (
    _ConfirmationWaitComponent(),
    _ConfirmationCompletionComponent(),
    _ConfirmationReminderComponent(),
)


class _ConfirmationComponent:
    name = "confirmation"
    order = 30

    def __init__(
        self,
        extensions: tuple[_ConfirmationActionComponent, ...] = (),
    ) -> None:
        self._extensions = extensions

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        if not alert.confirmation or not alert.confirmation.enabled:
            return AutomationFragments()
        return AutomationFragments(actions=tuple(self._confirmation_actions(alert)))

    def _action_components(self) -> tuple[_ConfirmationActionComponent, ...]:
        return tuple(
            sorted(
                (*_CONFIRMATION_ACTION_COMPONENTS, *self._extensions),
                key=lambda component: (component.order, component.name),
            )
        )

    def _confirmation_actions(self, alert: AlertConfig) -> list[dict[str, Any]]:
        """Assemble native confirmation fragments into an action sequence."""
        confirmation = alert.confirmation
        if confirmation is None:
            return []
        components = self._action_components()
        fragments = [component.compose(alert, confirmation) for component in components]
        wait = next(
            (fragment.wait for fragment in fragments if fragment.wait is not None),
            None,
        )
        if wait is None:
            raise ValueError("confirmation action registry must provide a wait")
        completion_actions = tuple(
            action
            for fragment in fragments
            if fragment.completion is not None
            for action in fragment.completion
        )
        reminders = next(
            (fragment.reminders for fragment in fragments if fragment.reminders is not None),
            None,
        )
        steps = _ActionStepBuilder(alert)
        outcome_branches = _confirmation_outcome_branches(
            completion_actions,
            steps,
        )
        reminder_action = _CONFIRMATION_REMINDER_BUILDER.build(
            alert,
            reminders,
            wait,
            outcome_branches,
            steps,
        )
        timeout_sequence = [
            *([reminder_action] if reminder_action else []),
            *_confirmation_terminal_actions(steps),
        ]
        return [
            steps.report(
                "waiting",
                "confirmation_waiting",
                message="Waiting for confirmation",
            ),
            wait,
            {
                "choose": [
                    *outcome_branches,
                ],
                "default": timeout_sequence,
            },
        ]


def _confirmation_outcome_branches(
    completion_actions: tuple[dict[str, Any], ...],
    steps: _ActionStepBuilder,
) -> tuple[dict[str, Any], ...]:
    """Build shared confirmation and cancellation outcomes."""
    return (
        {
            "conditions": [{
                "condition": "template",
                "value_template": "{{ wait.trigger.id == 'confirmation' }}",
            }],
            "sequence": list(completion_actions),
        },
        {
            "conditions": [{
                "condition": "template",
                "value_template": "{{ wait.trigger.id == 'cancel_run' }}",
            }],
            "sequence": _confirmation_terminal_actions(steps, cancelled=True),
        },
    )


def _confirmation_terminal_actions(
    steps: _ActionStepBuilder,
    *,
    cancelled: bool = False,
) -> list[dict[str, Any]]:
    """Report one terminal confirmation outcome."""
    status = "cancelled" if cancelled else "confirmation_timeout"
    action = "confirmation_cancelled" if cancelled else "confirmation_timeout"
    message = "Automation run cancelled" if cancelled else "Confirmation timed out"
    return [
        steps.report(
            status,
            action,
            message=message,
            details={"action": action},
        ),
        {"stop": "Confirmation ended"},
    ]


class _PostSendComponent:
    name = "post_send"
    order = 25

    def compose(self, alert: AlertConfig) -> AutomationFragments:
        post_send = alert.post_send_actions
        if not post_send or not post_send.get("enabled", False):
            return AutomationFragments()
        steps = _ActionStepBuilder(alert)
        actions = [_copy_native_value(action) for action in post_send.get("actions", [])]
        return AutomationFragments(
            actions=tuple(
                item
                for action in actions
                for item in steps.recorded_action(action)
            )
        )


_SEND_COMPONENT = _SendComponent()
_CONFIRMATION_REMINDER_BUILDER = _ConfirmationReminderBuilder()


AUTOMATION_COMPONENTS: tuple[AutomationComponent, ...] = (
    _TriggerComponent(),
    _ConditionComponent(),
    _SEND_COMPONENT,
    _ConfirmationComponent(),
    _PostSendComponent(),
)


def component_registry(
    extensions: tuple[AutomationComponent, ...] = (),
) -> tuple[AutomationComponent, ...]:
    """Return built-ins and extensions in stable composition order."""
    return tuple(
        sorted(
            (*AUTOMATION_COMPONENTS, *extensions),
            key=lambda component: (component.order, component.name),
        )
    )


def compose_automation(
    alert: AlertConfig | dict[str, Any],
    components: tuple[AutomationComponent, ...] | None = None,
) -> AutomationFragments:
    """Compose typed fragments from the ordered component registry."""
    alert = _validated_alert(alert)
    fragments = [component.compose(alert) for component in component_registry(components or ())]
    triggers = tuple(trigger for fragment in fragments for trigger in fragment.triggers)
    conditions = tuple(condition for fragment in fragments for condition in fragment.conditions)
    actions = tuple(action for fragment in fragments for action in fragment.actions)
    if not triggers:
        raise ValueError(f"alert {alert.id!r} must define at least one evaluation trigger")
    return AutomationFragments(
        triggers=triggers,
        conditions=conditions,
        actions=actions,
    )


async def async_validate_alerts(
    hass: HomeAssistant,
    alerts: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Validate generated alert automations with Home Assistant's schema."""
    def condition_items(alert: dict[str, Any]) -> list[dict[str, Any]]:
        monitor = alert.get("monitor", {})
        conditions = monitor.get("conditions", {}) if isinstance(monitor, dict) else {}
        items = conditions.get("items", []) if isinstance(conditions, dict) else []
        return items if isinstance(items, list) else []

    for alert in alerts:
        monitor = alert.get("monitor", {})
        condition_options = monitor.get("conditions", {}) if isinstance(monitor, dict) else {}
        for index, condition in enumerate(condition_options.get("items", [])):
            if condition.get("condition") != "numeric_state":
                continue
            condition_path = f"Alert {alert['id']!r} conditions[{index}]"
            if not any(key in condition for key in ("above", "below")):
                raise HomeAssistantError(f"{condition_path} (numeric_state) requires at least one of 'above' or 'below'.")
            if "for" in condition:
                raise HomeAssistantError(f"{condition_path} (numeric_state) does not support 'for'; use a state condition when a duration is required.")

    generated_alerts = [
        alert
        for alert in alerts
        if _validated_alert(alert).monitor.enabled_triggers
    ]
    generated = [
        (alert, automation)
        for alert in generated_alerts
        for automation in generate_automations(alert)
    ]
    document = [automation for _alert, automation in generated]
    validated = await async_validate_config(hass, {"automation": document})
    if len(validated["automation"]) != len(document):
        paths = "; ".join(
            f"Alert {alert['id']!r}: "
            + ", ".join(f"conditions[{index}] ({condition.get('condition', 'unknown')})" for index, condition in enumerate(condition_items(alert)))
            for alert in generated_alerts
        )
        raise HomeAssistantError(
            f"Generated HA Notifications automation failed Home Assistant validation; one or more automations were omitted. Condition paths: {paths or 'none'}"
        )
    failures = [
        f"Alert {alert['id']!r} generated automation {automation['id']!r} has "
        f"validation status {item.validation_status.value!r}"
        + (
            "; condition paths: "
            + ", ".join(
                f"conditions[{condition_index}] ({condition.get('condition', 'unknown')})"
                for condition_index, condition in enumerate(condition_items(alert))
            )
            if item.validation_status == ValidationStatus.FAILED_CONDITIONS
            else ""
        )
        for (alert, automation), item in zip(generated, validated["automation"])
        if item.validation_status != ValidationStatus.OK
    ]
    if failures:
        raise HomeAssistantError("Generated HA Notifications automation failed Home Assistant validation: " + "; ".join(failures))
    return document


def render_automation(
    alert: AlertConfig | dict[str, Any],
    fragments: AutomationFragments,
) -> dict[str, Any]:
    """Render composed fragments as one native Home Assistant automation."""
    alert = _validated_alert(alert)
    steps = _ActionStepBuilder(alert)
    sequence = [
        steps.report(
            "started",
            "automation_started",
            details={
                "action": "automation_started",
                "started_by": {
                    "platform": (
                        "{{ trigger.platform if trigger is defined and "
                        "trigger.platform is defined else '' }}"
                    ),
                    "id": (
                        "{{ trigger.id if trigger is defined and "
                        "trigger.id is defined else '' }}"
                    ),
                    "description": (
                        "{{ (trigger | default({})).description | "
                        "default('', true) }}"
                    ),
                    "entity_id": (
                        "{{ trigger.entity_id if trigger is defined and "
                        "trigger.entity_id is defined else '' }}"
                    ),
                    "from_state": (
                        "{{ trigger.from_state.state if trigger is defined and "
                        "trigger.from_state is defined and trigger.from_state "
                        "else '' }}"
                    ),
                    "to_state": (
                        "{{ trigger.to_state.state if trigger is defined and "
                        "trigger.to_state is defined and trigger.to_state "
                        "else '' }}"
                    ),
                    "event_type": (
                        "{{ trigger.event.event_type if trigger is defined and "
                        "trigger.platform == 'event' and trigger.event is defined "
                        "and trigger.event else '' }}"
                    ),
                },
            },
        ),
        *fragments.actions,
    ]
    if not alert.confirmation or not alert.confirmation.enabled:
        sequence.append(
            steps.report(
                "completed",
                "automation_completed",
                details={"action": "automation_completed"},
            )
        )
    alert_conditions = list(fragments.conditions)
    automation_triggers = [dict(trigger) for trigger in fragments.triggers]
    actions = sequence
    automation_conditions = alert_conditions
    if alert_conditions:
        trigger_ids = [
            trigger.get("id", str(index))
            for index, trigger in enumerate(automation_triggers)
        ]
        all_trigger_ids = trigger_ids
        all_trigger_condition = {
            "condition": "trigger",
            "id": all_trigger_ids,
        }
        active_trigger_condition = {
            "condition": "or",
            "conditions": [
                *([{
                    "condition": "trigger",
                    "id": trigger_ids,
                }] if trigger_ids else []),
                {
                    "condition": "template",
                    "value_template": (
                        "{{ trigger is not defined or trigger.platform is none }}"
                    ),
                },
            ],
        }
        not_conditions = {
            "condition": "not",
            "conditions": _copy_native_value(alert_conditions),
        }
        active_conditions = [
            *_copy_native_value(alert_conditions),
            active_trigger_condition,
        ]
        automation_conditions = [{
            "condition": "or",
            "conditions": [
                {"condition": "and", "conditions": active_conditions},
                {
                    "condition": "and",
                    "conditions": [all_trigger_condition, not_conditions],
                },
            ],
        }]
        inactive_report = steps.report(
            "inactive",
            "automation_inactive",
            message="Condition inactive",
            details={"action": "automation_inactive"},
            flow_id="{{ context.id }}",
            include_run_id=False,
        )
        actions = [{
            "choose": [{
                "conditions": [all_trigger_condition, not_conditions],
                "sequence": [inactive_report],
            }, {
                "conditions": [{
                    "condition": "or",
                    "conditions": [
                        {
                            "condition": "and",
                            "conditions": [
                                *_copy_native_value(alert_conditions),
                                active_trigger_condition,
                            ],
                        },
                        {
                            "condition": "template",
                            "value_template": (
                                "{{ trigger is not defined or trigger.platform is none }}"
                            ),
                        },
                    ],
                }],
                "sequence": sequence,
            }],
            "default": [],
        }]
    return {
        "id": automation_id(alert),
        "alias": f"HA Notifications: {alert.name or alert.id}",
        "description": GENERATED_DESCRIPTION,
        "initial_state": alert.enabled,
        "mode": "parallel" if alert_conditions else alert.monitor.automation_mode,
        "triggers": automation_triggers,
        "conditions": automation_conditions,
        "actions": actions,
    }


def generate_automation(
    alert: AlertConfig | dict[str, Any],
    components: tuple[AutomationComponent, ...] | None = None,
) -> dict[str, Any]:
    """Generate one Home Assistant automation for an alert."""
    validated = _validated_alert(alert)
    return render_automation(validated, compose_automation(validated, components))


def generate_automations(
    alert: AlertConfig | dict[str, Any],
    components: tuple[AutomationComponent, ...] | None = None,
) -> list[dict[str, Any]]:
    """Generate the single Home Assistant automation owned by an alert."""
    validated = _validated_alert(alert)
    if not validated.monitor.enabled_triggers:
        return []
    generated = [generate_automation(validated, components)]
    inactive = validated.monitor.inactive
    if inactive.enabled and inactive.items:
        steps = _ActionStepBuilder(validated)
        actions = [
            steps.report(
                "inactive", "inactive_trigger", message="Configured inactive trigger fired",
                include_run_id=False,
            ),
            {
                "action": "ha_notifications.command",
                "data": {"alert_id": validated.id, "command": COMMAND_CANCEL_RUN},
            },
        ]
        if inactive.clear_notification:
            actions.append({
                "action": "ha_notifications.clear",
                "data": {
                    "alert_id": validated.id,
                    "alert_name": validated.name,
                    **_SEND_COMPONENT.notification_mapping(validated.notification),
                },
            })
        generated.append({
            "id": f"{automation_id(validated)}_inactive",
            "alias": f"HA Notifications: {validated.name or validated.id} inactive",
            "description": GENERATED_DESCRIPTION,
            "initial_state": validated.enabled,
            "mode": "queued",
            "triggers": _copy_native_value(inactive.items),
            "conditions": [],
            "actions": actions,
        })
    return generated


def _validated_alert(alert: AlertConfig | dict[str, Any]) -> AlertConfig:
    """Accept persisted mappings while keeping automation on validated models."""
    return alert if isinstance(alert, AlertConfig) else AlertConfig.model_validate(alert)


def _follow_up_actions(
    alert: AlertConfig,
    confirmation: ConfirmationConfig,
    steps: _ActionStepBuilder,
) -> list[dict[str, Any]]:
    """Convert configured confirmation actions to native HA actions."""
    notification_action: dict[str, Any] | None = None
    notification = confirmation.notification
    if (
        notification.enabled is not False
        and (
            notification.action
            or notification.target is not None
            or notification.title is not None
            or notification.message is not None
            or notification.data is not None
        )
    ):
        notification = _confirmation_notification_mapping(notification, alert.notification.target)
        data = dict(notification.get("data", {}))
        message = data.pop("message", None)
        if isinstance(message, str) and message:
            data["template_message"] = "{% raw %}" + message + "{% endraw %}"
            data["confirmation_device_id"] = "{{ wait.trigger.event.data.device_id | default('', true) }}"
            data["confirmation_user_id"] = "{{ wait.trigger.event.context.user_id | default('', true) }}"
        if data:
            notification["data"] = data
        notification_action = steps.send({
            **notification,
            "history_reason": "confirmation_notification",
        })
    native_actions = [_copy_native_value(action) for action in confirmation.actions]
    actions = [notification_action] if notification_action is not None else []
    for action in native_actions:
        actions.extend(steps.recorded_action(action))
    return actions


def _confirmation_notification_mapping(
    notification: ConfirmationNotificationConfig,
    fallback_target: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Convert a confirmation notification to the managed service payload."""
    action: dict[str, Any] = {}
    target = notification.target if notification.target is not None else fallback_target
    if target:
        action["target"] = dict(target)
    data = dict(notification.data or {})
    if notification.title is not None:
        data.setdefault("title", notification.title)
    if notification.message is not None:
        data.setdefault("message", notification.message)
    if data:
        action["data"] = data
    action.update(notification.__pydantic_extra__ or {})
    return action


def _copy_native_value(value: Any) -> Any:
    """Create fresh containers for repeated Home Assistant native values."""
    if isinstance(value, dict):
        return {key: _copy_native_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_copy_native_value(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_copy_native_value(item) for item in value)
    return value


def automation_id(alert: AlertConfig | dict[str, Any]) -> str:
    """Return the stable automation ID for an alert."""
    alert_id = alert.id if isinstance(alert, AlertConfig) else alert["id"]
    return f"ha_notifications_{alert_id}"



